language: node_js
sudo: false
node_js:
  - "11"
install:
  - npm install
script:
  - npm i -g ionic
  - npm run lint-fix
  - ionic build --prod --service-worker
deploy:
  provider: pages
  local-dir: www
  committer-from-gh: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master